# Generated by Django 4.1.3 on 2022-11-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='body',
            field=models.TextField(),
        ),
    ]
